### ISSUE TITLE
在vivo x5xl机型上报错

### ISSUE THREAD

**Issue by calciferer** [Bilibili/MagicaSakura#34]
app已经上线了，只有在这个机型会报错，不知道什么原因。

android.view.InflateException: Binary XML file line #32: Error inflating class com.bilibili.magicasakura.widgets.TintRadioButton
	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at cn.geekdream.jhglsy.fragments.BaseFragment.onCreateView(BaseFragment.java)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java)
	at android.support.v4.view.ViewPager.populate(ViewPager.java)
	at android.support.v4.view.ViewPager.populate(ViewPager.java)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1616)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:729)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:601)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1616)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:729)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:601)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1616)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:729)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:601)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2391)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2469)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1385)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1655)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1262)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6456)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5351)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	... 62 more
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
	at android.content.res.Resources.getValue(Resources.java:1159)
	at android.content.res.VivoResources.getValue(VivoResources.java:175)
	at android.content.res.Resources.getColor(Resources.java:831)
	at cn.geekdream.jhglsy.JhglsyApplication.replaceColor(JhglsyApplication.java)
	at com.bilibili.magicasakura.utils.ThemeUtils.replaceColor(ThemeUtils.java)
	at com.bilibili.magicasakura.utils.DrawableUtils.getAttrColor(DrawableUtils.java)
	at com.bilibili.magicasakura.utils.DrawableUtils.getAttrColorFilter(DrawableUtils.java)
	at com.bilibili.magicasakura.utils.StateListDrawableInflateImpl.inflateDrawable(StateListDrawableInflateImpl.java)
	at com.bilibili.magicasakura.utils.DrawableUtils.createFromXmlInner(DrawableUtils.java)
	at com.bilibili.magicasakura.utils.DrawableUtils.createDrawable(DrawableUtils.java)
	at com.bilibili.magicasakura.utils.TintManager.getDrawable(TintManager.java)
	at com.bilibili.magicasakura.widgets.AppCompatCompoundButtonHelper.loadFromAttribute(AppCompatCompoundButtonHelper.java)
	at com.bilibili.magicasakura.widgets.TintRadioButton.<init>(TintRadioButton.java)
	at com.bilibili.magicasakura.widgets.TintRadioButton.<init>(TintRadioButton.java)
	... 65 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.constructNative(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at cn.geekdream.jhglsy.fragments.BaseFragment.onCreateView(BaseFragment.java)
	at android.support.v4.app.Fragment.performCreateView(Fragment.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java)
	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java)
	at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java)
	at android.support.v4.view.ViewPager.populate(ViewPager.java)
	at android.support.v4.view.ViewPager.populate(ViewPager.java)
	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1616)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:729)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:601)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
	at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1616)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:729)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:601)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1616)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:729)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:601)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5411)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:332)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2391)
	at android.view.View.measure(View.java:16926)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2469)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1385)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1655)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1262)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6456)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
	at android.view.Choreographer.doCallbacks(Choreographer.java:591)
	at android.view.Choreographer.doFrame(Choreographer.java:560)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)

**Comment by xyczero** [comment]
必崩吗？希望把radiobutton使用的相关资源贴出来看一下
