### ISSUE TITLE
添加IntButton在布局的时候报错

### ISSUE THREAD

**Issue by hlz1991** [Bilibili/MagicaSakura#64]
布局：
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".MainActivity">

    <com.bilibili.magicasakura.widgets.TintButton
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="123"/>
</LinearLayout>
错误：Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.bilibili.magicasakura.widgets.TintButton

我添加了依赖implementation 'com.bilibili:magicasakura:0.1.8@aar'
内部的属性也没错，所以不太清楚为啥会报这个错误，本人用的是4.4.2夜神模拟器跑的

**Comment by xyczero** [comment]
整个布局加载只有TintButton出错了？那可能需要你debug看下TintButton初始化时具体发生的错误了

**Comment by hlz1991** [comment]
> 
> 
> 整个布局加载只有TintButton出错了？那可能需要你debug看下TintButton初始化时具体发生的错误了

我把依赖删除，使用库的形式添加magicasakura，在TintButton内打断点，也是在4.4.2夜神模拟器运行，竟然没有崩溃，成功跑起来了。所以，这到底是啥原因崩溃的。

**Comment by xyczero** [comment]
😂那通过依赖的形式打断点看看呢

**Comment by hlz1991** [comment]
> 
> 
> joy那通过依赖的形式打断点看看呢

 Caused by: java.lang.NoClassDefFoundError: android.support.v4.graphics.drawable.DrawableWrapper
        at com.bilibili.magicasakura.utils.ThemeUtils.getWrapperDrawable(ThemeUtils.java:270)
        at com.bilibili.magicasakura.utils.ThemeUtils.containsNinePatch(ThemeUtils.java:245)
        at com.bilibili.magicasakura.widgets.AppCompatBackgroundHelper.recoverPadding(AppCompatBackgroundHelper.java:197)
        at com.bilibili.magicasakura.widgets.AppCompatBackgroundHelper.setBackgroundDrawable(AppCompatBackgroundHelper.java:122)
        at com.bilibili.magicasakura.widgets.AppCompatBackgroundHelper.loadFromAttribute(AppCompatBackgroundHelper.java:65)
        at com.bilibili.magicasakura.widgets.TintButton.<init>(TintButton.java:59)
        at com.bilibili.magicasakura.widgets.TintButton.<init>(TintButton.java:48)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.hlz.magicasakura.MainActivity.onCreate(MainActivity.java:23) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5019) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
依赖下断点在这里报错了。4.4.2夜神模拟器运行
